# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72413739baa4e777609152ed8a20093ca8ff048b36d6b606cc44907bc1e99c0fa4875e02ffb2fc03ba556223671e534c5d1378b0e08de507a00d0cc6ef4ecb5c

test:
  secret_key_base: c41b1d7fccad3d76e29f2fc62568cf0129326aaf27a0b3ec4911ac83f7b39ac78b38a9d105f20fc98a16a8cc6040242fc93f5486ecbb04d76cbda2e08cc13c9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
